### PR TITLE
Use CMake install

### LINKED ISSUE #733: [glm] Include dirs not found when using cmake_paths generator
### Package and Environment Details
  * Package Name/Version: **glm/0.9.9.4**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio-15**
  * Conan version: **conan 1.9.1**
  * Python version: **Python 3.7.1**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Description
When I link the glm library to my own target, the compiler doesn't find the correct include folder.
In short: `#include <glm/glm.hpp>` doesn't work as that file can't be found.
I'm using the cmake_paths generator. The relevant parts of my CMakeLists.txt file look like this:
```
cmake_minimum_required(VERSION 3.7)
project(glmtest)
include(${CMAKE_SOURCE_DIR}/build/conan_paths.cmake)
add_executable(glmtest src/main.cpp)
find_package(GLM REQUIRED)
target_link_libraries(glmtest PRIVATE glm)
```
The output says that the package is found and that it worked to link the library. It's just the includes that can't be found. It even produces these messages:
```
** GLM ALREADY FOUND BY CONAN!
** FOUND GLM INCLUDE:  C:/Users/Anton/.conan/data/glm/0.9.9.4/g-truc/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
```
This is the message I get when trying to compile:
`fatal error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory`

These are the commands I run:
```
conan install .. -s build_type=Debug --build missing
cmake .. -G "Visual Studio 15 2017 Win64"
cmake --build . --config Debug
```

I can note that GLFW, which is linked to the same target, works.

### PR DESCRIPTION
**Pull request by mmha**
Switches to the `cmake install` mechanism so the CMake package and PkgConfig install properly.

Upstreaming of the CMake patch is tracked on g-truc/glm#900.

closes: https://github.com/bincrafters/community/issues/733

### CODE REVIEW

**Comment by Croydon** [comment]
Personally, I would like to wait until it is released upstream

WDYT @uilianries?

**Comment by uilianries** [comment]
Hi @mmha !

Thanks for you contribution, but where did find that patch?

However, I agree with @Croydon! I would prefer keeping the version as it is. If you need cmake support, I suggest you using Conan CMake Generator:

    conan install -r bincrafters glm/0.9.9.5@bincrafters/stable -g cmake

Regards!

**Comment by uilianries** [comment]
@mmha now I see your PR there in glm. This is a great contribution, but let's wait to be accepted by the upstream first.

**Comment by mmha** [comment]
> Thanks for you contribution, but where did find that patch?

I wrote it. That's also my issue upstream :)

> I suggest you using Conan CMake Generator

The CMake generator + `CONAN_PKG::glm` works fine probably, but I'd strongly prefer if I wouldn't have to fall back to it. Ideally I'd just have an (optional) `conan_basic_setup()` at the beginning and the rest stays vanilla CMake with `find_package` and potentially `FindFoo.cmake`. That way conan stays noninvasive and I can write the packaging for my application for Linux distributions without requiring conan.

**Comment by mmha** [comment]
I'm fine with waiting until the next release :+1:

**Comment by uilianries** [comment]
> The CMake generator + CONAN_PKG::glm works fine probably, but I'd strongly prefer if I wouldn't have to fall back to it. Ideally I'd just have an (optional) conan_basic_setup() at the beginning and the rest stays vanilla CMake with find_package and potentially FindFoo.cmake. That way conan stays noninvasive and I can write the packaging for my application for Linux distributions without requiring conan.

@mmha have you ever tried [cmake_find_package generator](https://docs.conan.io/en/latest/integrations/cmake/cmake_find_package_generator.html)? It will produce Findgml.cmake

**Comment by mmha** [comment]
Sure, but that doesn't solve the problem. The upstream way of consuming is:

```cmake
find_package(glm)
target_link_libraries(app PRIVATE glm) # No namespace
```

the `cmake_find_package` generator creates `glm::glm` as an imported target:

```cmake
find_package(glm)
target_link_libraries(app PRIVATE glm::glm)
```

And even if the names were the same, it wouldn't be a generic solution. As of now I will probably create a `Findglm.cmake` on my own and put it inside my source tree to make it work with both system and conan installations of glm.

In other words, waiting for both PRs to land is not a blocking issue. Just a bit annoying to work around. So I'm fine with waiting.

**Comment by uilianries** [comment]
Thanks for explaining and sharing!

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
